; --- BASE SETTINGS (Applies to everything) ---
[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; --- ENVIRONMENT 1: The Motor Test ---
[env:motor_test]
; Tells PlatformIO to ONLY compile the motor_test folder
build_src_filter = +<motor_test/> 

; --- ENVIRONMENT 2: The Final Application ---
[env:final_app]
; Tells PlatformIO to ONLY compile the final_app folder
build_src_filter = +<final_app/>

; --- ENVIRONMENT 3: The Kinematics ---
[env:kinematics]
; Tells PlatformIO to ONLY compile the kinematics folder
build_src_filter = +<kinematics/>