; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-DBOARD_HAS_PSRAM
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv

[env:motor_test]
build_src_filter = +<motor_test/>


[env:final_app]
build_src_filter = +<final_app/>


[env:kinematics]
build_src_filter = +<kinematics/>


[env:basic_line_following]
build_src_filter = +<basic_line/>
lib_deps = adafruit/Adafruit TCS34725@^1.4.4

